project:
  type: website

website:
  title: "ecmbblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/EmiliaCMB
format:
  html:
    toc: true
    df-print: paged
    theme: minty
    css: styles.css

editor: source

